## Airbnb Málaga. Achievement 6

### 6. Clean your data. Conduct some basic data cleaning and consistency checks in Jupyter to ensure your data is ready for further analysis.

In [3]:
# Importing libraries

import pandas as pd
import numpy as np
import os

In [4]:
# Creating path

path = r'C:\Users\Víctor A\Desktop\CAREER FOUNDRY\Immersion Achievement 6 Victor A.Gallardo\DATA'

In [5]:
# Importing Data

listings = pd.read_csv(os.path.join(path, 'listings.csv'), index_col = False)

In [6]:
# Checking dataframe

listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8976 entries, 0 to 8975
Data columns (total 75 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            8976 non-null   int64
 1   listing_url                                   8976 non-null   object
 2   scrape_id                                     8976 non-null   int64
 3   last_scraped                                  8976 non-null   object
 4   source                                        8976 non-null   object
 5   name                                          8976 non-null   object
 6   description                                   8714 non-null   object
 7   neighborhood_overview                         4420 non-null   object
 8   picture_url                                   8976 non-null   object
 9   host_id                                       8976 non-null   int64
 10  host_url                                      8976 non-null   object
 11  host_name                                     8976 non-null   object
 12  host_since                                    8976 non-null   object
 13  host_location                                 6926 non-null   object
 14  host_about                                    5203 non-null   object
 15  host_response_time                            8395 non-null   object
 16  host_response_rate                            8395 non-null   object
 17  host_acceptance_rate                          8594 non-null   object
 18  host_is_superhost                             8568 non-null   object
 19  host_thumbnail_url                            8976 non-null   object
 20  host_picture_url                              8976 non-null   object
 21  host_neighbourhood                            1070 non-null   object
 22  host_listings_count                           8976 non-null   int64
 23  host_total_listings_count                     8976 non-null   int64
 24  host_verifications                            8976 non-null   object
 25  host_has_profile_pic                          8976 non-null   object
 26  host_identity_verified                        8976 non-null   object
 27  neighbourhood                                 4420 non-null   object
 28  neighbourhood_cleansed                        8976 non-null   object
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      8976 non-null   float64
 31  longitude                                     8976 non-null   float64
 32  property_type                                 8976 non-null   object
 33  room_type                                     8976 non-null   object
 34  accommodates                                  8976 non-null   int64
 35  bathrooms                                     8650 non-null   float64
 36  bathrooms_text                                8973 non-null   object
 37  bedrooms                                      8910 non-null   float64
 38  beds                                          8649 non-null   float64
 39  amenities                                     8976 non-null   object
 40  price                                         8586 non-null   object
 41  minimum_nights                                8976 non-null   int64
 42  maximum_nights                                8976 non-null   int64
 43  minimum_minimum_nights                        8976 non-null   int64
 44  maximum_minimum_nights                        8976 non-null   int64
 45  minimum_maximum_nights                        8976 non-null   int64
 46  maximum_maximum_nights                        8976 non-null   int64
 47  minimum_nights_avg_ntm                        8976 non-null   float64
 48  maximum_nights_avg_ntm                        8976 non-null   float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              8916 non-null   object
 51  availability_30                               8976 non-null   int64
 52  availability_60                               8976 non-null   int64
 53  availability_90                               8976 non-null   int64
 54  availability_365                              8976 non-null   int64
 55  calendar_last_scraped                         8976 non-null   object
 56  number_of_reviews                             8976 non-null   int64
 57  number_of_reviews_ltm                         8976 non-null   int64
 58  number_of_reviews_l30d                        8976 non-null   int64
 59  first_review                                  7763 non-null   object
 60  last_review                                   7763 non-null   object
 61  review_scores_rating                          7763 non-null   float64
 62  review_scores_accuracy                        7756 non-null   float64
 63  review_scores_cleanliness                     7756 non-null   float64
 64  review_scores_checkin                         7756 non-null   float64
 65  review_scores_communication                   7756 non-null   float64
 66  review_scores_location                        7756 non-null   float64
 67  review_scores_value                           7756 non-null   float64
 68  license                                       8821 non-null   object
 69  instant_bookable                              8976 non-null   object
 70  calculated_host_listings_count                8976 non-null   int64
 71  calculated_host_listings_count_entire_homes   8976 non-null   int64
 72  calculated_host_listings_count_private_rooms  8976 non-null   int64
 73  calculated_host_listings_count_shared_rooms   8976 non-null   int64
 74  reviews_per_month                             7763 non-null   float64
dtypes: float64(17), int64(23), object(35)
memory usage: 5.1+ MB

In [7]:
listings.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,638401413782978130,https://www.airbnb.com/rooms/638401413782978130,20240630141205,2024-07-01,city scrape,Capitán - Apartamento en el centro de Málaga,Magnificent apartment in the heart of Malaga w...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,382146507,...,4.95,4.98,4.85,VFT/MA/52526,t,63,63,0,0,3.99
1,593807685540946920,https://www.airbnb.com/rooms/593807685540946920,20240630141205,2024-07-01,city scrape,"Balcón Victoria, 4 bedrooms with balcony in th...","Balcón Victoria, 4 rooms in Historic Center. I...",NaN,https://a0.muscache.com/pictures/prohost-api/H...,11733642,...,4.92,4.83,4.67,VFT/MA/45175,t,20,20,0,0,0.46
2,689209787389564671,https://www.airbnb.com/rooms/689209787389564671,20240630141205,2024-07-01,city scrape,"Lovely spacious 2 bedroom, 2 bathroom with ter...","Set in the perfect location, this stylish, com...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,13967638,...,4.64,4.73,4.55,CTC-2017080773,f,2,1,1,0,0.60
3,1169368107504912867,https://www.airbnb.com/rooms/1169368107504912867,20240630141205,2024-07-01,city scrape,Cathedral Penthouse with Terrace,Enjoy the cathedral from the terrace or living...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,4884962,...,NaN,NaN,NaN,VUT/MA/63833,t,17,17,0,0,NaN
4,53218911,https://www.airbnb.com/rooms/53218911,20240630141205,2024-06-30,city scrape,excelente estudio cerca del Carrefour,NaN,NaN,https://a0.muscache.com/pictures/d60ac57b-d9fb...,413971511,...,4.65,3.24,3.12,Exempt,t,4,4,0,0,0.53

In [8]:
# Excluding irrelevant columns

listings = listings[[
    'id', 'name', 'description', 'host_id', 'host_since', 'host_location', 
    'host_response_time', 'host_response_rate', 'host_acceptance_rate', 
    'host_is_superhost', 'host_total_listings_count', 'host_identity_verified', 
    'neighbourhood_cleansed', 'latitude', 'longitude', 'property_type', 
    'room_type', 'accommodates', 'bathrooms', 'bedrooms', 'beds', 'amenities', 
    'price', 'minimum_nights', 'maximum_nights', 'minimum_minimum_nights', 
    'maximum_minimum_nights', 'minimum_maximum_nights', 'maximum_maximum_nights', 
    'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'has_availability', 
    'number_of_reviews', 'number_of_reviews_ltm', 'number_of_reviews_l30d', 
    'first_review', 'last_review', 'license', 'instant_bookable', 
    'calculated_host_listings_count', 'calculated_host_listings_count_entire_homes', 
    'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms', 
    'reviews_per_month'
]]

In [9]:
listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8976 entries, 0 to 8975
Data columns (total 44 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            8976 non-null   int64
 1   name                                          8976 non-null   object
 2   description                                   8714 non-null   object
 3   host_id                                       8976 non-null   int64
 4   host_since                                    8976 non-null   object
 5   host_location                                 6926 non-null   object
 6   host_response_time                            8395 non-null   object
 7   host_response_rate                            8395 non-null   object
 8   host_acceptance_rate                          8594 non-null   object
 9   host_is_superhost                             8568 non-null   object
 10  host_total_listings_count                     8976 non-null   int64
 11  host_identity_verified                        8976 non-null   object
 12  neighbourhood_cleansed                        8976 non-null   object
 13  latitude                                      8976 non-null   float64
 14  longitude                                     8976 non-null   float64
 15  property_type                                 8976 non-null   object
 16  room_type                                     8976 non-null   object
 17  accommodates                                  8976 non-null   int64
 18  bathrooms                                     8650 non-null   float64
 19  bedrooms                                      8910 non-null   float64
 20  beds                                          8649 non-null   float64
 21  amenities                                     8976 non-null   object
 22  price                                         8586 non-null   object
 23  minimum_nights                                8976 non-null   int64
 24  maximum_nights                                8976 non-null   int64
 25  minimum_minimum_nights                        8976 non-null   int64
 26  maximum_minimum_nights                        8976 non-null   int64
 27  minimum_maximum_nights                        8976 non-null   int64
 28  maximum_maximum_nights                        8976 non-null   int64
 29  minimum_nights_avg_ntm                        8976 non-null   float64
 30  maximum_nights_avg_ntm                        8976 non-null   float64
 31  has_availability                              8916 non-null   object
 32  number_of_reviews                             8976 non-null   int64
 33  number_of_reviews_ltm                         8976 non-null   int64
 34  number_of_reviews_l30d                        8976 non-null   int64
 35  first_review                                  7763 non-null   object
 36  last_review                                   7763 non-null   object
 37  license                                       8821 non-null   object
 38  instant_bookable                              8976 non-null   object
 39  calculated_host_listings_count                8976 non-null   int64
 40  calculated_host_listings_count_entire_homes   8976 non-null   int64
 41  calculated_host_listings_count_private_rooms  8976 non-null   int64
 42  calculated_host_listings_count_shared_rooms   8976 non-null   int64
 43  reviews_per_month                             7763 non-null   float64
dtypes: float64(8), int64(17), object(19)
memory usage: 3.0+ MB

### Change data types

In [11]:
# Converting price column from string to float format

# Remove the dollar sign and commas from the price column
listings.loc[:, 'price'] = listings['price'].replace({'\$': '', ',': ''}, regex=True)

# Convert the price column to float
listings.loc[:, 'price'] = listings['price'].astype(float)

In [12]:
# Converting date columns to datetime format 

# Convert 'host_since' to datetime 
listings.loc[:, 'host_since'] = pd.to_datetime(listings['host_since'])

# Convert 'first_review' to datetime
listings.loc[:, 'first_review'] = pd.to_datetime(listings['first_review'])

# Convert 'last_review' to datetime 
listings.loc[:, 'last_review'] = pd.to_datetime(listings['last_review'])

In [13]:
# Converting boolean columns to boolean format 

# Define a mapping function that converts 't', 'f' to boolean and handles 'nan'
def convert_to_boolean(value):
    if value == 't':
        return True
    elif value == 'f':
        return False
    else:
        return None  # Handle 'nan' and other unexpected values

# Apply the mapping function to each column using .loc to ensure direct modification
listings.loc[:, 'host_is_superhost'] = listings['host_is_superhost'].apply(convert_to_boolean).astype('boolean')
listings.loc[:, 'host_identity_verified'] = listings['host_identity_verified'].apply(convert_to_boolean).astype('boolean')
listings.loc[:, 'has_availability'] = listings['has_availability'].apply(convert_to_boolean).astype('boolean')
listings.loc[:, 'instant_bookable'] = listings['instant_bookable'].apply(convert_to_boolean).astype('boolean')

In [14]:
# Convert 'host_response_rate' and 'host_acceptance_rate' from percentage strings to float
listings.loc[:, 'host_response_rate'] = listings['host_response_rate'].str.rstrip('%').astype(float) / 100
listings.loc[:, 'host_acceptance_rate'] = listings['host_acceptance_rate'].str.rstrip('%').astype(float) / 100

In [15]:
# Display unique values for 'host_response_rate' and 'host_acceptance_rate'
unique_response_rates = listings['host_response_rate'].unique()
unique_acceptance_rates = listings['host_acceptance_rate'].unique()

unique_response_rates, unique_acceptance_rates

(array([1.0, 0.95, nan, 0.93, 0.73, 0.0, 0.5, 0.99, 0.98, 0.9, 0.71, 0.7,
        0.97, 0.67, 0.42, 0.94, 0.8, 0.92, 0.89, 0.82, 0.57, 0.75, 0.96,
        0.3, 0.64, 0.14, 0.25, 0.43, 0.56, 0.6, 0.78, 0.08, 0.88, 0.2, 0.1,
        0.17, 0.83, 0.86, 0.4, 0.33, 0.84, 0.69, 0.32, 0.87, 0.63, 0.91,
        0.79, 0.81, 0.85, 0.77, 0.48, 0.38, 0.52, 0.54, 0.58], dtype=object),
 array([1.0, 0.43, 0.99, 0.78, 0.06, nan, 0.86, 0.58, 0.94, 0.0, 0.98, 0.5,
        0.91, 0.57, 0.63, 0.96, 0.25, 0.93, 0.55, 0.73, 0.89, 0.79, 0.68,
        0.4, 0.92, 0.87, 0.71, 0.97, 0.1, 0.95, 0.18, 0.22, 0.85, 0.82,
        0.13, 0.07, 0.33, 0.39, 0.6, 0.83, 0.88, 0.64, 0.74, 0.75, 0.65,
        0.11, 0.77, 0.67, 0.49, 0.76, 0.37, 0.24, 0.8, 0.29, 0.7, 0.45,
        0.46, 0.9, 0.41, 0.59, 0.2, 0.62, 0.21, 0.81, 0.52, 0.69, 0.3,
        0.84, 0.35, 0.61, 0.27, 0.38, 0.02, 0.48, 0.47, 0.66, 0.72, 0.36,
        0.53, 0.05, 0.56, 0.14, 0.54, 0.17, 0.44, 0.12, 0.26], dtype=object))

In [16]:
listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8976 entries, 0 to 8975
Data columns (total 44 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            8976 non-null   int64
 1   name                                          8976 non-null   object
 2   description                                   8714 non-null   object
 3   host_id                                       8976 non-null   int64
 4   host_since                                    8976 non-null   object
 5   host_location                                 6926 non-null   object
 6   host_response_time                            8395 non-null   object
 7   host_response_rate                            8395 non-null   object
 8   host_acceptance_rate                          8594 non-null   object
 9   host_is_superhost                             8568 non-null   object
 10  host_total_listings_count                     8976 non-null   int64
 11  host_identity_verified                        8976 non-null   object
 12  neighbourhood_cleansed                        8976 non-null   object
 13  latitude                                      8976 non-null   float64
 14  longitude                                     8976 non-null   float64
 15  property_type                                 8976 non-null   object
 16  room_type                                     8976 non-null   object
 17  accommodates                                  8976 non-null   int64
 18  bathrooms                                     8650 non-null   float64
 19  bedrooms                                      8910 non-null   float64
 20  beds                                          8649 non-null   float64
 21  amenities                                     8976 non-null   object
 22  price                                         8586 non-null   object
 23  minimum_nights                                8976 non-null   int64
 24  maximum_nights                                8976 non-null   int64
 25  minimum_minimum_nights                        8976 non-null   int64
 26  maximum_minimum_nights                        8976 non-null   int64
 27  minimum_maximum_nights                        8976 non-null   int64
 28  maximum_maximum_nights                        8976 non-null   int64
 29  minimum_nights_avg_ntm                        8976 non-null   float64
 30  maximum_nights_avg_ntm                        8976 non-null   float64
 31  has_availability                              8916 non-null   object
 32  number_of_reviews                             8976 non-null   int64
 33  number_of_reviews_ltm                         8976 non-null   int64
 34  number_of_reviews_l30d                        8976 non-null   int64
 35  first_review                                  7763 non-null   object
 36  last_review                                   7763 non-null   object
 37  license                                       8821 non-null   object
 38  instant_bookable                              8976 non-null   object
 39  calculated_host_listings_count                8976 non-null   int64
 40  calculated_host_listings_count_entire_homes   8976 non-null   int64
 41  calculated_host_listings_count_private_rooms  8976 non-null   int64
 42  calculated_host_listings_count_shared_rooms   8976 non-null   int64
 43  reviews_per_month                             7763 non-null   float64
dtypes: float64(8), int64(17), object(19)
memory usage: 3.0+ MB

In [17]:
# Configure pandas to display all columns

pd.set_option('display.max_columns', None)

In [18]:
listings.head()

,id,name,description,host_id,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_identity_verified,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,has_availability,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,638401413782978130,Capitán - Apartamento en el centro de Málaga,Magnificent apartment in the heart of Malaga w...,382146507,2020-12-29 00:00:00,"Málaga, Spain",within an hour,1.0,1.0,False,72,True,Centro,36.722069,-4.420914,Entire rental unit,Entire home/apt,4,1.0,2.0,2.0,"[""Hair dryer"", ""Kitchen"", ""Clothing storage: c...",178.0,2,1125,2,4,1125,1125,2.3,1125.0,True,100,58,4,2022-06-12 00:00:00,2024-06-26 00:00:00,VFT/MA/52526,True,63,63,0,0,3.99
1,593807685540946920,"Balcón Victoria, 4 bedrooms with balcony in th...","Balcón Victoria, 4 rooms in Historic Center. I...",11733642,2014-01-28 00:00:00,Spain,within an hour,1.0,1.0,False,24,True,Centro,36.727180,-4.413260,Entire rental unit,Entire home/apt,7,2.0,4.0,5.0,"[""Hair dryer"", ""TV"", ""Free street parking"", ""K...",219.0,1,365,1,5,1125,1125,2.5,1125.0,True,12,4,1,2022-05-17 00:00:00,2024-06-27 00:00:00,VFT/MA/45175,True,20,20,0,0,0.46
2,689209787389564671,"Lovely spacious 2 bedroom, 2 bathroom with ter...","Set in the perfect location, this stylish, com...",13967638,2014-04-06 00:00:00,"Málaga, Spain",within a few hours,1.0,0.43,False,3,True,Centro,36.727710,-4.412884,Entire rental unit,Entire home/apt,4,2.0,2.0,2.0,"[""Hair dryer"", ""Wine glasses"", ""TV"", ""Kitchen""...",141.0,2,365,1,2,365,365,2.0,365.0,True,11,6,0,2023-01-02 00:00:00,2024-04-13 00:00:00,CTC-2017080773,False,2,1,1,0,0.60
3,1169368107504912867,Cathedral Penthouse with Terrace,Enjoy the cathedral from the terrace or living...,4884962,2013-01-28 00:00:00,"Andalusia, Spain",within an hour,1.0,1.0,False,38,True,Centro,36.719241,-4.420821,Entire rental unit,Entire home/apt,10,2.0,2.0,6.0,"[""Hair dryer"", ""Portable heater"", ""Room-darken...",162.0,3,365,1,3,365,1000,3.0,971.5,True,0,0,0,NaT,NaT,VUT/MA/63833,True,17,17,0,0,NaN
4,53218911,excelente estudio cerca del Carrefour,NaN,413971511,2021-07-19 00:00:00,"Andalusia, Spain",within an hour,0.95,0.99,False,35,True,Palma-Palmilla,36.737370,-4.434390,Entire rental unit,Entire home/apt,2,1.0,0.0,1.0,"[""Hair dryer"", ""Room-darkening shades"", ""Lockb...",53.0,2,365,2,2,1125,1125,2.0,1125.0,True,17,4,0,2021-11-13 00:00:00,2024-05-16 00:00:00,Exempt,True,4,4,0,0,0.53

In [19]:
# Check the current unique values in the boolean columns
print("Unique values in 'host_is_superhost':", listings['host_is_superhost'].unique())
print("Unique values in 'host_identity_verified':", listings['host_identity_verified'].unique())
print("Unique values in 'has_availability':", listings['has_availability'].unique())
print("Unique values in 'instant_bookable':", listings['instant_bookable'].unique())

Unique values in 'host_is_superhost': [False True <NA>]
Unique values in 'host_identity_verified': [True False]
Unique values in 'has_availability': [True <NA> False]
Unique values in 'instant_bookable': [True False]

In [20]:
# Setting the dtype explicitly to Pandas' nullable boolean type
listings['host_is_superhost'] = listings['host_is_superhost'].astype('boolean')
listings['host_identity_verified'] = listings['host_identity_verified'].astype('boolean')
listings['has_availability'] = listings['has_availability'].astype('boolean')
listings['instant_bookable'] = listings['instant_bookable'].astype('boolean')

In [21]:
listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8976 entries, 0 to 8975
Data columns (total 44 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            8976 non-null   int64
 1   name                                          8976 non-null   object
 2   description                                   8714 non-null   object
 3   host_id                                       8976 non-null   int64
 4   host_since                                    8976 non-null   object
 5   host_location                                 6926 non-null   object
 6   host_response_time                            8395 non-null   object
 7   host_response_rate                            8395 non-null   object
 8   host_acceptance_rate                          8594 non-null   object
 9   host_is_superhost                             8568 non-null   boolean
 10  host_total_listings_count                     8976 non-null   int64
 11  host_identity_verified                        8976 non-null   boolean
 12  neighbourhood_cleansed                        8976 non-null   object
 13  latitude                                      8976 non-null   float64
 14  longitude                                     8976 non-null   float64
 15  property_type                                 8976 non-null   object
 16  room_type                                     8976 non-null   object
 17  accommodates                                  8976 non-null   int64
 18  bathrooms                                     8650 non-null   float64
 19  bedrooms                                      8910 non-null   float64
 20  beds                                          8649 non-null   float64
 21  amenities                                     8976 non-null   object
 22  price                                         8586 non-null   object
 23  minimum_nights                                8976 non-null   int64
 24  maximum_nights                                8976 non-null   int64
 25  minimum_minimum_nights                        8976 non-null   int64
 26  maximum_minimum_nights                        8976 non-null   int64
 27  minimum_maximum_nights                        8976 non-null   int64
 28  maximum_maximum_nights                        8976 non-null   int64
 29  minimum_nights_avg_ntm                        8976 non-null   float64
 30  maximum_nights_avg_ntm                        8976 non-null   float64
 31  has_availability                              8916 non-null   boolean
 32  number_of_reviews                             8976 non-null   int64
 33  number_of_reviews_ltm                         8976 non-null   int64
 34  number_of_reviews_l30d                        8976 non-null   int64
 35  first_review                                  7763 non-null   object
 36  last_review                                   7763 non-null   object
 37  license                                       8821 non-null   object
 38  instant_bookable                              8976 non-null   boolean
 39  calculated_host_listings_count                8976 non-null   int64
 40  calculated_host_listings_count_entire_homes   8976 non-null   int64
 41  calculated_host_listings_count_private_rooms  8976 non-null   int64
 42  calculated_host_listings_count_shared_rooms   8976 non-null   int64
 43  reviews_per_month                             7763 non-null   float64
dtypes: boolean(4), float64(8), int64(17), object(15)
memory usage: 2.8+ MB

In [54]:
# Ver los primeros valores de las columnas de fechas
print(listings['host_since'].head())
print(listings['first_review'].head())
print(listings['last_review'].head())

0    2020-12-29 00:00:00
1    2014-01-28 00:00:00
2    2014-04-06 00:00:00
3    2013-01-28 00:00:00
4    2021-07-19 00:00:00
Name: host_since, dtype: object
0    2022-06-12 00:00:00
1    2022-05-17 00:00:00
2    2023-01-02 00:00:00
3                    NaT
4    2021-11-13 00:00:00
Name: first_review, dtype: object
0    2024-06-26 00:00:00
1    2024-06-27 00:00:00
2    2024-04-13 00:00:00
3                    NaT
4    2024-05-16 00:00:00
Name: last_review, dtype: object

In [56]:
# Intentar convertir las columnas a datetime y forzar la conversión
listings['host_since'] = pd.to_datetime(listings['host_since'], errors='coerce')
listings['first_review'] = pd.to_datetime(listings['first_review'], errors='coerce')
listings['last_review'] = pd.to_datetime(listings['last_review'], errors='coerce')

# Verificar los tipos de datos después de la conversión
print(listings[['host_since', 'first_review', 'last_review']].dtypes)

host_since      datetime64[ns]
first_review    datetime64[ns]
last_review     datetime64[ns]
dtype: object

In [58]:
listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8976 entries, 0 to 8975
Data columns (total 44 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            8976 non-null   int64
 1   name                                          8976 non-null   object
 2   description                                   8714 non-null   object
 3   host_id                                       8976 non-null   int64
 4   host_since                                    8976 non-null   datetime64[ns]
 5   host_location                                 6926 non-null   object
 6   host_response_time                            8395 non-null   object
 7   host_response_rate                            8395 non-null   object
 8   host_acceptance_rate                          8594 non-null   object
 9   host_is_superhost                             8568 non-null   boolean
 10  host_total_listings_count                     8976 non-null   int64
 11  host_identity_verified                        8976 non-null   boolean
 12  neighbourhood_cleansed                        8976 non-null   object
 13  latitude                                      8976 non-null   float64
 14  longitude                                     8976 non-null   float64
 15  property_type                                 8976 non-null   object
 16  room_type                                     8976 non-null   object
 17  accommodates                                  8976 non-null   int64
 18  bathrooms                                     8650 non-null   float64
 19  bedrooms                                      8910 non-null   float64
 20  beds                                          8649 non-null   float64
 21  amenities                                     8976 non-null   object
 22  price                                         8586 non-null   object
 23  minimum_nights                                8976 non-null   int64
 24  maximum_nights                                8976 non-null   int64
 25  minimum_minimum_nights                        8976 non-null   int64
 26  maximum_minimum_nights                        8976 non-null   int64
 27  minimum_maximum_nights                        8976 non-null   int64
 28  maximum_maximum_nights                        8976 non-null   int64
 29  minimum_nights_avg_ntm                        8976 non-null   float64
 30  maximum_nights_avg_ntm                        8976 non-null   float64
 31  has_availability                              8916 non-null   boolean
 32  number_of_reviews                             8976 non-null   int64
 33  number_of_reviews_ltm                         8976 non-null   int64
 34  number_of_reviews_l30d                        8976 non-null   int64
 35  first_review                                  7763 non-null   datetime64[ns]
 36  last_review                                   7763 non-null   datetime64[ns]
 37  license                                       8821 non-null   object
 38  instant_bookable                              8976 non-null   boolean
 39  calculated_host_listings_count                8976 non-null   int64
 40  calculated_host_listings_count_entire_homes   8976 non-null   int64
 41  calculated_host_listings_count_private_rooms  8976 non-null   int64
 42  calculated_host_listings_count_shared_rooms   8976 non-null   int64
 43  reviews_per_month                             7763 non-null   float64
dtypes: boolean(4), datetime64[ns](3), float64(8), int64(17), object(12)
memory usage: 2.8+ MB

### Missing values

In [70]:
# finding missing values
listings.isnull().sum()

id                                                 0
name                                               0
description                                      262
host_id                                            0
host_since                                         0
host_location                                   2050
host_response_time                               581
host_response_rate                               581
host_acceptance_rate                             382
host_is_superhost                                408
host_total_listings_count                          0
host_identity_verified                             0
neighbourhood_cleansed                             0
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                        326
bedrooms                                          66
beds                                             327
amenities                                          0
price                                            390
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
has_availability                                  60
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
first_review                                    1213
last_review                                     1213
license                                          155
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1213
dtype: int64

In [72]:
# Remove the 'host_location' column since every list is in Málaga
listings = listings.drop(columns=['host_location'])

# Verify that the column has been removed
listings.head()

,id,name,description,host_id,host_since,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_identity_verified,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,has_availability,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,638401413782978130,Capitán - Apartamento en el centro de Málaga,Magnificent apartment in the heart of Malaga w...,382146507,2020-12-29,within an hour,1.0,1.0,False,72,True,Centro,36.722069,-4.420914,Entire rental unit,Entire home/apt,4,1.0,2.0,2.0,"[""Hair dryer"", ""Kitchen"", ""Clothing storage: c...",178.0,2,1125,2,4,1125,1125,2.3,1125.0,True,100,58,4,2022-06-12,2024-06-26,VFT/MA/52526,True,63,63,0,0,3.99
1,593807685540946920,"Balcón Victoria, 4 bedrooms with balcony in th...","Balcón Victoria, 4 rooms in Historic Center. I...",11733642,2014-01-28,within an hour,1.0,1.0,False,24,True,Centro,36.727180,-4.413260,Entire rental unit,Entire home/apt,7,2.0,4.0,5.0,"[""Hair dryer"", ""TV"", ""Free street parking"", ""K...",219.0,1,365,1,5,1125,1125,2.5,1125.0,True,12,4,1,2022-05-17,2024-06-27,VFT/MA/45175,True,20,20,0,0,0.46
2,689209787389564671,"Lovely spacious 2 bedroom, 2 bathroom with ter...","Set in the perfect location, this stylish, com...",13967638,2014-04-06,within a few hours,1.0,0.43,False,3,True,Centro,36.727710,-4.412884,Entire rental unit,Entire home/apt,4,2.0,2.0,2.0,"[""Hair dryer"", ""Wine glasses"", ""TV"", ""Kitchen""...",141.0,2,365,1,2,365,365,2.0,365.0,True,11,6,0,2023-01-02,2024-04-13,CTC-2017080773,False,2,1,1,0,0.60
3,1169368107504912867,Cathedral Penthouse with Terrace,Enjoy the cathedral from the terrace or living...,4884962,2013-01-28,within an hour,1.0,1.0,False,38,True,Centro,36.719241,-4.420821,Entire rental unit,Entire home/apt,10,2.0,2.0,6.0,"[""Hair dryer"", ""Portable heater"", ""Room-darken...",162.0,3,365,1,3,365,1000,3.0,971.5,True,0,0,0,NaT,NaT,VUT/MA/63833,True,17,17,0,0,NaN
4,53218911,excelente estudio cerca del Carrefour,NaN,413971511,2021-07-19,within an hour,0.95,0.99,False,35,True,Palma-Palmilla,36.737370,-4.434390,Entire rental unit,Entire home/apt,2,1.0,0.0,1.0,"[""Hair dryer"", ""Room-darkening shades"", ""Lockb...",53.0,2,365,2,2,1125,1125,2.0,1125.0,True,17,4,0,2021-11-13,2024-05-16,Exempt,True,4,4,0,0,0.53

### 7. Understand your data. Develop a basic understanding of your data set by reviewing the variables and performing basic descriptive statistical analysis

In [81]:
# Numerical columns

listings.describe()

,id,host_id,host_since,host_total_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,8.976000e+03,8.976000e+03,8976,8976.000000,8976.000000,8976.000000,8976.000000,8650.000000,8910.000000,8649.000000,8976.000000,8976.000000,8976.000000,8976.000000,8976.000000,8976.000000,8976.000000,8976.000000,8976.000000,8976.000000,8976.000000,7763,7763,8976.000000,8976.000000,8976.000000,8976.000000,7763.000000
mean,5.217140e+17,1.979661e+08,2017-12-15 10:38:39.786096640,56.951760,36.720254,-4.421389,4.053587,1.310694,1.672952,2.479824,3.088792,525.985851,2.688725,5.412322,639.114973,731.283200,3.924889,687.396858,42.930927,12.950980,1.150067,2021-07-19 16:20:20.559062528,2024-02-17 03:57:03.779466752,22.613191,21.033868,1.569630,0.008356,1.525055
min,9.603300e+04,4.555300e+04,2009-10-13 00:00:00,1.000000,36.646012,-4.584345,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,2011-08-25 00:00:00,2013-12-31 00:00:00,1.000000,0.000000,0.000000,0.000000,0.010000
25%,3.774567e+07,4.102521e+07,2015-08-11 00:00:00,2.000000,36.718080,-4.429416,2.000000,1.000000,1.000000,1.000000,1.000000,160.000000,1.000000,2.000000,120.000000,365.000000,2.000000,365.000000,3.000000,1.000000,0.000000,2019-08-15 00:00:00,2024-02-26 00:00:00,1.000000,1.000000,0.000000,0.000000,0.380000
50%,6.561254e+17,1.307236e+08,2017-05-17 00:00:00,8.000000,36.722164,-4.422601,4.000000,1.000000,1.000000,2.000000,2.000000,365.000000,2.000000,4.000000,365.000000,999.000000,2.600000,960.200000,14.000000,5.000000,0.000000,2022-06-12 00:00:00,2024-06-02 00:00:00,5.000000,4.000000,0.000000,0.000000,1.000000
75%,9.650197e+17,3.292660e+08,2020-01-20 00:00:00,54.000000,36.725268,-4.417434,5.000000,1.500000,2.000000,3.000000,3.000000,1125.000000,2.000000,5.000000,1125.000000,1125.000000,3.700000,1125.000000,49.000000,18.000000,2.000000,2023-08-06 00:00:00,2024-06-17 00:00:00,26.000000,25.000000,0.000000,0.000000,2.140000
max,1.189767e+18,5.864050e+08,2024-06-29 00:00:00,6437.000000,36.875649,-4.278520,16.000000,11.000000,25.000000,50.000000,699.000000,1125.000000,500.000000,1000.000000,1125.000000,1125.000000,500.000000,1125.000000,906.000000,182.000000,15.000000,2024-06-30 00:00:00,2024-06-30 00:00:00,194.000000,194.000000,37.000000,6.000000,13.550000
std,4.748903e+17,1.797676e+08,NaN,160.524854,0.013847,0.024977,2.206075,0.679784,1.225179,2.024958,12.795038,428.048555,9.090595,18.004329,466.357692,437.353574,11.895301,436.676033,73.733284,18.148279,1.777948,NaN,NaN,37.965137,37.691198,4.969394,0.178003,1.572874

In [85]:
# boolean columns

boolean_columns = ['host_is_superhost', 'host_identity_verified', 'has_availability', 'instant_bookable']
listings[boolean_columns].describe()

,host_is_superhost,host_identity_verified,has_availability,instant_bookable
count,8568,8976,8916,8976
unique,2,2,2,2
top,False,True,True,True
freq,6350,8755,8914,5614

In [90]:
# Exporting listing

listings.to_csv(os.path.join(path,'listings_cleaned.csv'), index=False)